name: deploy


on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: ./scripts/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PROFILE_DATA }}
    - name: Select Xcode
      run: sudo Xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -project TestApp.xcodeproj -configuration Release -scheme TestApp -derivedDataPath DerivedData -archivePath DerivedData/Archive/TestApp archive
    - name: Export Archive
      run: xcodebuild -exportArchive -archivePath DerivedData/Archive/TestApp.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: xcrun altool --upload-app --type ios --file DerivedData/ipa/TestApp.ipa --username "${{ secrets.APP_STORE_CONNECT_USERNAME }}" --password "${{ secrets.APP_STORE_CONNECT_PASSWORD }}" --verbose
